src/CourtJustice/CourtJustice.Web/Controllers/RemainTasksController.cs
using CourtJustice.Domain.Models;
using CourtJustice.Infrastructure.Helpers;
using CourtJustice.Infrastructure.Interfaces;
using CourtJustice.Infrastructure.Repositories;
using CourtJustice.Infrastructure.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CourtJustice.Web.Controllers
{
    public class RemainTasksController : BaseController<RemainTasksController>
    {
        private readonly IRemainTaskRepository _remainTaskRepository;
        private readonly IEmployeeRepository _employeeRepository;

        public RemainTasksController(IRemainTaskRepository remainTaskRepository, IEmployeeRepository employeeRepository)
        {
            _remainTaskRepository = remainTaskRepository;
            _employeeRepository = employeeRepository;
        }

        //[HttpPost]
        //public async Task<IActionResult> GetWithPaging()
        //{
        //    try
        //    {
        //        var appUser = SessionHelper.GetObjectFromJson<AppUser>(HttpContext.Session, "userObject");
        //        //var bucketId = Request.Form["bucketId"].FirstOrDefault();
        //        //var employerCode = Request.Form["employerCode"].FirstOrDefault();
        //        var draw = Request.Form["draw"].FirstOrDefault();
        //        var start = Request.Form["start"].FirstOrDefault();
        //        var length = Request.Form["length"].FirstOrDefault();
        //        var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
        //        var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
        //        var searchValue = Request.Form["search[value]"].FirstOrDefault();
        //        int pageSize = length != null ? Convert.ToInt32(length) : 0;
        //        int skip = start != null ? Convert.ToInt32(start) : 0;

        //        int recordsTotal = await _remainTaskRepository.GetRecordCount(appUser.UserId,  searchValue!);
        //        var data = await _remainTaskRepository.GetPaging(appUser.UserId, skip, pageSize, searchValue!);
        //        var jsonData = new { draw, recordsFiltered = recordsTotal, recordsTotal, data };
        //        return Ok(jsonData);
        //    }
        //    catch
        //    {
        //        throw;
        //    }
        //}

        private async Task<List<RemainTask>> GetAll()
        {
            var results = await _remainTaskRepository.GetAll();
            return results.ToList();
        }
        public async Task<IActionResult> Index()
        {
            var tasks = await GetAll();
            return View(tasks);
        }
        public async Task<IActionResult> Create()
        {
            var employees = await _employeeRepository.GetAll();
            List<SelectListItem> selects = new();
            foreach (var item in employees)
            {
                selects.Add(new SelectListItem
                {
                    Text = $"{item.EmployeeName}",
                    Value = item.EmployeeCode.ToString(),
                });
            }
            ViewBag.Employees = selects;
            return View(new RemainTask() );
        }
        [HttpPost]
        public async Task<IActionResult> Create(RemainTask model)
        {
            try
            {
                var appUser = SessionHelper.GetObjectFromJson<AppUser>(HttpContext.Session, "userObject");
                model.TaskDatetime= DateTime.Now;
                model.AssignFrom = appUser.UserId;
                await _remainTaskRepository.Create(model);
                _notify.Success($"ข้อความเตือนความจำ is Created.");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                var employees = await _employeeRepository.GetAll();
                List<SelectListItem> selects = new();
                foreach (var item in employees)
                {
                    selects.Add(new SelectListItem
                    {
                        Text = $"{item.EmployeeName}",
                        Value = item.EmployeeCode.ToString(),
                    });
                }
                ViewBag.Employees = selects;
                return View(model);
            }
        }

        [HttpDelete, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _remainTaskRepository.Delete(id);
                var results = await GetAll();
                var html = RenderRazorViewHelper.RenderRazorViewToString(this, "_ViewTable", results);
                return new JsonResult(new { isValid = true, message = "", html });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { isValid = false, message = ex.Message });

            }

        }

    }
}

src/CourtJustice/CourtJustice.Web/Views/RemainTasks/Create.cshtml
@using CourtJustice.Domain.Models;
@model RemainTask

@{
    ViewData["Title"] = "ข้อความเตือน";

}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-3">
                    <h3 class="mb-3">เพิ่ม @ViewData["Title"]</h3>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="Create">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label class="control-label" asp-for="AssignTo"></label>
                                    <select class="form-control dropdown" id="ddlEmployee" asp-for="AssignTo" asp-items="@ViewBag.Employees">
                                    </select>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label asp-for="TaskDetail" class="control-label"></label>
                                    <input asp-for="TaskDetail" class="form-control" />
                                    <span asp-validation-for="TaskDetail" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <a asp-action="Index" class="btn btn-light">Back</a>
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script src="~/js/pages/remain_task.js" asp-append-version="true"></script>
    }
}

src/CourtJustice/CourtJustice.Web/Views/RemainTasks/Index.cshtml
@using CourtJustice.Domain.Models;
@model IEnumerable<RemainTask>
@{
    ViewData["Title"] = "ข้อความเตือน";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-3">
                    <h3 class="mb-3">@ViewData["Title"]</h3>
                    <a asp-action="Create" class="btn btn-success text-white"><i class="fa fa-plus"></i> Create New</a>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div id="view-table">
                    @await Html.PartialAsync("_ViewTable", Model)
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Hidden("hdDeleteRoute", Url.Action("Delete", "RemainTasks"))
@section scripts{
    <script src="~/js/pages/remain_task.js" asp-append-version="true"></script>
}

src/CourtJustice/CourtJustice.Web/Views/RemainTasks/_ViewTable.cshtml
@using CourtJustice.Domain.Models;
@model IEnumerable<RemainTask>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="tbl_loanee">
        <thead>
            <tr class="bg-primary text-white" role="row">
                <th>
                    @Html.DisplayNameFor(model => model.TaskDatetime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TaskDetail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AssignTo)
                </th>
                   <th>
                    @Html.DisplayNameFor(model => model.AssignFrom)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.TaskDatetime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TaskDetail)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AssignTo)
                    </td>
                        <td>
                        @Html.DisplayFor(modelItem => item.AssignFrom)
                    </td>
                    <td class="w150">
                        <div class="d-inline">
                            <a class="btn btn-sm btn-primary text-white" asp-action="Edit" asp-route-id="@item.TaskId"><i class='fa fa-edit'></i></a>
                            <a class="btn btn-sm btn-danger text-white" onclick="confirmDelete('@item.TaskId');"><i class='fa fa-trash'></i></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>