src/CourtJustice/CourtJustice.Web/Controllers/GuarantorsController.cs
using CourtJustice.Domain.Models;
using CourtJustice.Infrastructure.Helpers;
using CourtJustice.Infrastructure.Interfaces;
using CourtJustice.Infrastructure.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CourtJustice.Web.Controllers
{

    public class GuarantorsController : BaseController<GuarantorsController>
    {
        private readonly IGuarantorRepository _guarantorRepository;

        public GuarantorsController(IGuarantorRepository guarantorRepository)
        {
            _guarantorRepository = guarantorRepository;
        }

        public IActionResult Index()
        {
            return View();
        }


        private async Task<List<Guarantor>> GetAll()
        {
            var results = await _guarantorRepository.GetAll();
            return results.ToList();
        }

        public IActionResult Create()
        {
            return View(new Guarantor());
        }


        [HttpGet]
        public async Task<IActionResult> AddOrEdit(int id =0)
        {
            if (id == 0)
            {
                return View(new Guarantor());
            }
            else
            {
                var guarantor = await _guarantorRepository.GetByKey(id);
                return View(guarantor);
            }
        }


        [HttpPost]
        public async Task<JsonResult> AddOrEdit([FromBody] Guarantor model)
        {
            var isExisting = _guarantorRepository.IsExisting(model.GuarantorCode);
            if (isExisting)
            {
                await _guarantorRepository.Update(model.GuarantorCode, model);
            }
            else
            {
                await _guarantorRepository.Create(model);
            }
            var guarantor = await _guarantorRepository.GetByCusId(model.CusId);
            var html = RenderRazorViewHelper.RenderRazorViewToString(this, "_GuarantorCard", guarantor);
            return new JsonResult(new { isValid = true, html });
        }


        [HttpDelete, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id, string cusId)
        {
            try
            {
                await _guarantorRepository.Delete(id);
                var guarantor = await _guarantorRepository.GetByCusId(cusId);
                var html = RenderRazorViewHelper.RenderRazorViewToString(this, "_GuarantorCard", guarantor);
                return new JsonResult(new { isValid = true, message = "", html });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { isValid = false, message = ex.Message });
            }

        }

        [HttpGet]
        public async Task<JsonResult> GetByCusId(string id)
        {
            var guarantor = await _guarantorRepository.GetByCusId(id);
            var html = RenderRazorViewHelper.RenderRazorViewToString(this, "_GuarantorCard", guarantor);
            return new JsonResult(new { isValid = true, message = "", html });
        }


    }
}

src/CourtJustice/CourtJustice.Web/Views/Guarantors/AddOrEdit.cshtml
@using CourtJustice.Domain.Models;
@model Guarantor
@{
    Layout = null;
    ViewData["Title"] = "ผู้ค้ำประกัน";
    var showAddressSetLookupUrl = @Url.Action("IndexAddressSetLookup", "AddressSets");
    var getAddressSetLookupUrl = @Url.Action("GetWithPaging", "AddressSets");
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="AddOrEdit" onsubmit="return AddOrEditGuarantor(this);">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input asp-for="GuarantorCode" class="form-control" type="hidden" />
                            <div class="row">

                                @if (String.IsNullOrEmpty(Model.IdCardNumber))
                                {

                                    <div class="form-group col-md-2">
                                        <label asp-for="IdCardNumber" class="control-label"></label>
                                        <input asp-for="IdCardNumber" class="form-control" />
                                        <span asp-validation-for="IdCardNumber" class="text-danger"></span>

                                    </div>
                                    
                                }
                                else
                                {

                                    <div class="form-group col-md-2">
                                        <label asp-for="IdCardNumber" class="control-label"></label>
                                        <input asp-for="IdCardNumber" class="form-control" readonly />
                                        <span asp-validation-for="IdCardNumber" class="text-danger"></span>

                                    </div>
                                }

                                <div class="form-group col-md-4">
                                    <label asp-for="FullName" class="control-label"></label>
                                    <input asp-for="FullName" class="form-control" />
                                    <span asp-validation-for="FullName" class="text-danger"></span>

                                </div>
                                <div class="form-group col-md-2">
                                    <label asp-for="PhoneNumber" class="control-label"></label>
                                    <input asp-for="PhoneNumber" class="form-control" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>


                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label asp-for="Address" class="control-label"></label>
                                    <div class="input-group">
                                        <input asp-for="Address" type="text" class="form-control" id="txtAddressSetLookup" />
                                        <span class="input-group-append">
                                            <a href="#" onclick="showLookup('0','@showAddressSetLookupUrl','@getAddressSetLookupUrl');" class="btn btn-primary text-white">...</a>
                                        </span>
                                    </div>
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-6">
                                    <label asp-for="AddressDetail" class="control-label"></label>
                                    <input asp-for="AddressDetail" class="form-control" />
                                    <span asp-validation-for="AddressDetail" class="text-danger"></span>
                                </div>

                            </div>
                            <div class="form-group">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@Html.Hidden("hdGetAddressSetById", Url.Action("GetAddressById", "AddressSets"))

src/CourtJustice/CourtJustice.Web/Views/Guarantors/_GuarantorCard.cshtml
@using CourtJustice.Domain.ViewModels;
@using System.Globalization;
@model IEnumerable<GuarantorViewModel>;
@{
    Layout = null;
    // var cultureInfor = new CultureInfo("th-TH");

}

<a class="btn btn-success btn-sm text-white" onclick="showInPopupXL('@Url.Action("AddOrEdit","Guarantors",null,Context.Request.Scheme)','เพิ่มข้อมูลผู้ค้ำประกัน')"><i class="fa fa-plus"></i> เพิ่มข้อมูล</a>


    <table class="table table-bordered table-hover data-table">
        <thead>
            <tr class="bg-primary text-white" role="row">

                @* <th>
                        @Html.DisplayNameFor(model => model.GuarantorCode)
                    </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.FullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AddressDetail)
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    @*  <td>
                            @Html.DisplayFor(modelItem => item.GuarantorCode)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddressDetail)
                    </td>
                    <td class="w150">
                        <div class="d-inline">
                            <a class="btn btn-sm btn-primary text-white" onclick="showInPopupXL('@Url.Action("AddOrEdit","Guarantors",new {id=item.GuarantorCode},Context.Request.Scheme)','แก้ไขข้อมูลผู้ค้ำประกัน')"><i class='fa fa-edit'></i></a>
                            <a class="btn btn-sm btn-danger text-white" onclick="confirmDeleteGuarantor('@Url.Action("Delete","Guarantors",new {id=item.GuarantorCode},Context.Request.Scheme)');"><i class='fa fa-trash'></i></a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>