src/CourtJustice/CourtJustice.Web/Controllers/LawyersController.cs
using CourtJustice.Domain.Models;
using CourtJustice.Infrastructure.Helpers;
using CourtJustice.Infrastructure.Interfaces;
using CourtJustice.Infrastructure.Repositories;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CourtJustice.Web.Controllers
{

    public class LawyersController : BaseController<LawyersController>
    {
        private readonly ILawyerRepository _lawyerRepository;
        private readonly IAppUserRepository _appUserRepository;

        public LawyersController(ILawyerRepository lawyerRepository, IAppUserRepository appUserRepository)
        {
            _lawyerRepository = lawyerRepository;
            _appUserRepository = appUserRepository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await GetAll());
        }

        private async Task<List<Lawyer>> GetAll()
        {
            var results = await _lawyerRepository.GetAll();
            return results.ToList();
        }


        public IActionResult Create()
        {
           
            return View(new Lawyer());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Lawyer model)
        {
            if (ModelState.IsValid)
            {
                await _lawyerRepository.Create(model);
                _notify.Success($"{model.LawyerName} is Created.");
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var model = await _lawyerRepository.GetByKey(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, Lawyer model)
        {
            var oldEntity = await _lawyerRepository.GetByKey(id);

            if (oldEntity == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _lawyerRepository.Update(id, model);

                var appUser = new AppUser
                {
                    UserId  =model.LawyerCode,
                    UserName = model.LawyerName,
                    Email = model.Email,
                    PhoneNumber = model.PhoneNumber,
                    IsActive = model.IsActive
                };
                await _appUserRepository.Update(id, appUser);

                _notify.Success($"{model.LawyerName} is Updated");

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpDelete, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
               // var count = await _groupUserRepository.CheckExistingAtUser(id);
               // if (count > 0)
              //  {
                   // return new JsonResult(new { isValid = false, message = "ไม่สามารถลบข้อมูลได้ \r\nเนื่องจากมีการใช้งานแล้ว!" });
              //  }
                await _lawyerRepository.Delete(id);
                //_notify.Success($"Delete is Success.");
                var results = await GetAll();
                var html = RenderRazorViewHelper.RenderRazorViewToString(this, "_ViewTable", results);
                return new JsonResult(new { isValid = true, message = "", html });
            }
            catch (Exception ex)
            {
                return new JsonResult(new { isValid = false, message = ex.Message });

            }

        }
    }
}

src/CourtJustice/CourtJustice.Web/Views/Lawyers/Create.cshtml
@using CourtJustice.Domain.Models;
@model Lawyer

@{
    ViewData["Title"] = "ข้อมูลทนายความ";
}

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-3">
                    <h3 class="mb-3">เพิ่ม @ViewData["Title"]</h3>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label asp-for="LawyerCode" class="control-label"></label>
                                    <input asp-for="LawyerCode" class="form-control" readonly />
                                    <span asp-validation-for="LawyerCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label asp-for="LawyerName" class="control-label"></label>
                                    <input asp-for="LawyerName" class="form-control" />
                                    <span asp-validation-for="LawyerName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label asp-for="Email" class="control-label"></label>
                                    <input asp-for="Email" class="form-control" type="email" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label asp-for="PhoneNumber" class="control-label"></label>
                                    <input asp-for="PhoneNumber" class="form-control" type="number" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label asp-for="Address" class="control-label"></label>
                                    <input asp-for="Address" class="form-control" />
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                            </div>

                          
                            <div class="form-group">
                                <a asp-action="Index" class="btn btn-light">Back</a>
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/CourtJustice/CourtJustice.Web/Views/Lawyers/Edit.cshtml
@using CourtJustice.Domain.Models;
@model Lawyer

@{
    ViewData["Title"] = "ข้อมูลทนายความ";
    var showAddressSetLookupUrl = @Url.Action("IndexAddressSetLookup", "AddressSets");
    var getAddressSetLookupUrl = @Url.Action("GetWithPaging", "AddressSets");
}

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-3">
                    <h3 class="mb-3">เพิ่ม @ViewData["Title"]</h3>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label asp-for="LawyerCode" class="control-label"></label>
                                    <input asp-for="LawyerCode" class="form-control" readonly />
                                    <span asp-validation-for="LawyerCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label asp-for="LawyerName" class="control-label"></label>
                                    <input asp-for="LawyerName" class="form-control" />
                                    <span asp-validation-for="LawyerName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label asp-for="Email" class="control-label"></label>
                                    <input asp-for="Email" class="form-control" type="email" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label asp-for="PhoneNumber" class="control-label"></label>
                                    <input asp-for="PhoneNumber" class="form-control" />
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label asp-for="Address" class="control-label"></label>
                                    <div class="input-group">
                                        <input asp-for="Address" type="text" class="form-control" id="txtAddressSetLookup" />
                                        <span class="input-group-append">
                                            <a href="#" onclick="showLookup('0','@showAddressSetLookupUrl','@getAddressSetLookupUrl');" class="btn btn-primary text-white">...</a>
                                        </span>
                                    </div>
                                    <span asp-validation-for="Address" class="text-danger"></span>
                                </div>
                                <div class="form-group col-md-6">
                                    <label asp-for="AddressDetail" class="control-label"></label>
                                    <input asp-for="AddressDetail" class="form-control" />
                                    <span asp-validation-for="AddressDetail" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                                </label>
                            </div>
                            <div class="form-group">
                                <a asp-action="Index" class="btn btn-light">Back</a>
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@Html.Hidden("hdGetAddressSetById", Url.Action("GetAddressById", "AddressSets"))
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/pages/address_lookup.js" asp-append-version="true"></script>
}

src/CourtJustice/CourtJustice.Web/Views/Lawyers/Index.cshtml
@using CourtJustice.Domain.Models;
@model IEnumerable<Lawyer>
@{
    ViewData["Title"] = "ข้อมูลทนายความ";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-3">
                    <h3 class="mb-3">@ViewData["Title"]</h3>
                    @*<a asp-action="Create" class="btn btn-success text-white"><i class="fa fa-plus"></i> Create New</a>*@
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div id="view-table">
                    @await Html.PartialAsync("_ViewTable", Model)
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Hidden("hdDeleteRoute", Url.Action("Delete", "Lawyers"))
@section scripts{
    <script src="~/js/pages/lawyer.js" asp-append-version="true"></script>
}

src/CourtJustice/CourtJustice.Web/Views/Lawyers/_ViewTable.cshtml
@using CourtJustice.Domain.Models;
@model IEnumerable<Lawyer>

<div class="table-responsive">
    <table class="table table-bordered table-hover data-table">
        <thead>
            <tr class="bg-primary text-white" role="row">
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.LawyerCode)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.LawyerName)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.AddressDetail)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.CreatedDateTime)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.UserCreated)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.UpdatedDateTime)
                </th>
                <th class="text-nowrap">
                    @Html.DisplayNameFor(model => model.UserUpdated)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.LawyerCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LawyerName)
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.Email)</td> 
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddressDetail)
                    </td>
                    <td>
                        @if (item.IsActive)
                        {
                            <div class="badge badge-outline-success badge-pill">ใช้งาน</div>
                        }
                        else
                        {
                            <div class="badge badge-outline-light badge-pill">ไม่ใช้งาน</div>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserCreated)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserUpdated)
                    </td>
                    <td class="w100">
                        <div class="d-inline">
                            <a class="btn btn-sm btn-primary text-white" asp-action="Edit" asp-route-id="@item.LawyerCode"><i class='fa fa-edit'></i></a>
                            @*<a class="btn btn-sm btn-danger text-white" onclick="confirmDelete('@item.LawyerCode');"><i class='fa fa-trash'></i></a>*@
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>